###################### Round 19: Austin GP ######################
year = 2025
driver_info = {
            "Oscar Piastri":
                "Birth: 6 April, 2001\n"
                "Nationality: Australian\n"
                "F1 Debut: 2023 - Bahrain\n"
                "Team: McLaren\n"
                "Car number: 81\n"
                "Number of races: 70\n"
                "Championships: 0\n"
                "Wins: 9\n"
                "Wins from Pole: 4\n"
                "Wins (Sprint Format): 2\n"
                "Podiums: 26\n"
                "Season position {year}: 3\n"
                "Season points {year}: 410\n"
                "GP Pole Positions: 6\n"
                "Fastest Laps: 9\n"
                "Total Points: 799\n"
                "Retirements (DNFs): 4\n"
                "Best Championship Finish: 3rd (2025)\n",

            "Lando Norris": 
                "Birth: November 13, 1999\n"
                "Nationality: British \n"
                "F1 Debut: 2019 Australian Grand Prix\n"
                "Team: McLaren\n"
                "Car number: 4\n"
                "Number of races: 152\n"
                "Championships: 0\n"
                "Wins: 11\n"
                "Wins from Pole: 5\n"
                "Sprint Wins: 2\n"
                "Podiums: 44\n"
                "Season position {year}: 1\n"
                "Season points {year}: 423\n"
                "GP Pole Positions: 16\n"
                "Fastest Laps: 18\n"
                "Total Points: 1430\n"
                "Retirements (DNFs): 14\n"
                "Best Championship Finish: 1st (2025)\n",

            "George Russell":
                "Birth: February 15, 1998\n"
                "Nationality: British \n"
                "F1 Debut: 2019 Australian Grand Prix\n"
                "Team: Mercedes\n"
                "Car number: 63\n"
                "Number of races: 152\n"
                "Championships: 0\n"
                "Wins: 5\n"
                "Sprint Wins: 1\n"
                "Wins from Pole: 4\n"
                "Podiums: 24\n"
                "Season position {year}: 4\n"
                "Season points {year}: 319\n"
                "GP Pole Positions: 7\n"
                "Fastest Laps: 11\n"
                "Total Points: 1033\n"
                "Retirements (DNFs): 19\n"
                "Best Championship Finish: 4th (2025)\n",

            "Kimi Antonelli":
                "Birth: August 25, 2006\n"
                "Nationality: Italian \n"
                "F1 Debut: 2025 Australian Grand Prix\n"
                "Team: Mercedes\n"
                "Car number: 14\n"
                "Number of races: 24\n"
                "Championships: 0\n"
                "Wins: 0\n"
                "Sprint Wins: 0\n"
                "Wins from Pole: 0\n"
                "Podiums: 3\n"
                "Season position {year}: 7\n"
                "Season points {year}: 150\n"
                "GP Pole Positions: 0\n"
                "Fastest Laps: 3\n"
                "Total Points: 150\n"
                "Retirements (DNFs): 4\n"
                "Best Championship Finish: 7th (2025)\n",
            
            "Max Verstappen":
                "Birth: September 30, 1997\n"
                "Nationality: Dutch\n"
                "F1 Debut: 2015 Australian Grand Prix\n"
                "Team: Red Bull Racing\n"
                "Car number: 1\n"
                "Number of races: 228\n"
                "Championships: 4\n"
                "Wins: 68\n"
                "Sprint Wins: 13\n"
                "Wins from Pole: 36\n"
                "Podiums: 122\n"
                "Season position {year}: 3\n"
                "Season points {year}: 306\n"
                "GP Pole Positions: 47\n"
                "Fastest Laps: 35\n"
                "Total Points: 3329.5\n"
                "Retirements (DNFs): 33\n"
                "Best Championship Finish: 1st (2021-2024)\n",

            "Charles Leclerc": 
                "Birth: October 16, 1997\n"
                "Nationality: Monegasque \n"
                "F1 Debut: 2018 Australian Grand Prix\n"
                "Team: Ferrari\n"
                "Car number: 16\n"
                "Number of races: 166\n"
                "Championships: 0\n"
                "Wins: 8\n"
                "Wins from Pole: 5\n"
                "Sprint Wins: 0\n"
                "Podiums: 49\n"
                "Season position {year}: 5\n"
                "Season points {year}: 192\n"
                "GP Pole Positions: 27\n"
                "Fastest Laps: 10\n"
                "Total Points: 1622\n"
                "Retirements (DNFs): 22\n"
                "Best Championship Finish: 2nd (2022)\n",
            
            "Lewis Hamilton":
                "Birth: January 7, 1985\n"
                "Nationality: British \n"
                "F1 Debut: 2007 Australian Grand Prix\n"
                "Team: Ferrari\n"
                "Car number: 44\n"
                "Number of races: 375\n"
                "Championships: 7\n"
                "Wins: 105\n"
                "Sprint Wins: 1\n"
                "Wins from Pole: 61\n"
                "Podiums: 202\n"
                "Season position {year}: 6\n"
                "Season points {year}: 142\n"
                "GP Pole Positions: 104\n"
                "Fastest Laps: 68\n"
                "Total Points: 5004.5\n"
                "Retirements (DNFs): 33\n"
                "Best Championship Finish: 1st\n" 
                "       (2008, 2014,2015, 2017-2020)\n",

            "Alexander Albon":
                "Birth: March 23, 1996\n"
                "Nationality: Thai\n"
                "F1 Debut: 2019 Australian Grand Prix\n"
                "Team: Williams\n"
                "Car number: 23\n"
                "Number of races: 123\n"
                "Championships: 0\n"
                "Wins: 0\n"
                "Wins from Pole: 0\n"
                "Sprint Wins: 0\n"
                "Podiums: 2\n"
                "Season position {year}: 8\n"
                "Season points {year}: 73\n"
                "GP Pole Positions: 0\n"
                "Fastest Laps: 0\n"
                "Total Points: 313\n"
                "Retirements (DNFs): 21\n"
                "Best Championship Finish: 7th (2020)\n",

            "Carlos Sainz":
                "Birth: September 1, 1994\n"
                "Nationality: Spanish\n"
                "F1 Debut: 2015 Australian Grand Prix\n"
                "Team: Williams\n"
                "Car number: 55\n"
                "Number of races: 224\n"
                "Championships: 0\n"
                "Wins: 4\n"
                "Sprint Wins: 0\n"
                "Wins from Pole: 3\n"
                "Podiums: 28\n"
                "Season position {year}: 11\n"
                "Season points {year}: 38\n"
                "GP Pole Positions: 6\n"
                "Fastest Laps: 4\n"
                "Total Points: 1310.5\n"
                "Retirements (DNFs): 41\n"
                "Best Championship Finish: 5th (2021)\n",

            "Fernando Alonso":
                "Birth: 29 July, 1981\n"
                "Nationality: Spanish\n"
                "F1 Debut: 2001 Australian Gran Prix\n"
                "Team: Aston Martin\n"
                "Car number: 14\n"
                "Number of races: 420\n"
                "Championships: 2\n"
                "Wins: 32\n"
                "Sprint Wins: 0\n"
                "Wins from Pole: 14\n"
                "Podiums: 106\n"
                "Season position {year}: 12\n"
                "Season points {year}: 37\n"
                "GP Pole Positions: 22\n"
                "Fastest Laps: 26\n"
                "Total Points: 2374\n"
                "Retirements (DNFs): 81\n"
                "Best Championship Finish: 1st\n"
                "                 (2005, 2006)\n",

        }
        